name: Sphinx build

on:
  pull_request:
  push:
  schedule:
    - cron: '0 16 * * 5'  # Every Friday 4pm
  workflow_dispatch:

# Drop permissions to minimum for security
permissions:
  contents: read

jobs:
  docs:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Set up Python 3.14
      uses: actions/setup-python@v6
      with:
        python-version: 3.14
    - name: Install dependencies
      run: |
        pip3 install -r docs/requirements.txt
    - name: Build documentation
      run: |
        make -C docs/ html
    - name: Store documentation
      uses: actions/upload-artifact@v4
      with:
        name: "wait_for_it_docs_html_${{ github.sha }}"
        path: docs/build/html/
        if-no-files-found: error
